import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  Collection,
  Expense,
  TeamMemberWithPayments,
  UnifiedTransaction,
  FestivalSettings,
} from '@/lib/types';
import { formatCurrencyPlain, formatDate, formatTime } from './format';

interface PDFExportData {
  festivalSettings: FestivalSettings | null;
  collections: Collection[];
  expenses: Expense[];
  teamMembers: TeamMemberWithPayments[];
  allTransactions: UnifiedTransaction[];
  summary: {
    totalMoneyReceived: number;
    totalExpenses: number;
    remainingBalance: number;
    totalTransactions: number;
    teamTotalPromised: number;
    teamTotalPaid: number;
    teamTotalPending: number;
    teamCompletedCount: number;
    teamTotalCount: number;
  };
  dateRange: { start: string | null; end: string | null };
  profileName: string;
}

function filterByDateRange<T extends { date: string }>(items: T[], start: string | null, end: string | null): T[] {
  if (!start && !end) return items;
  return items.filter((item) => {
    if (start && item.date < start) return false;
    if (end && item.date > end) return false;
    return true;
  });
}

const COLORS = {
  green: [22, 163, 74] as [number, number, number],
  red: [220, 38, 38] as [number, number, number],
  yellow: [245, 158, 11] as [number, number, number],
  dark: [30, 27, 22] as [number, number, number],
  gray: [107, 114, 128] as [number, number, number],
  lightGray: [243, 244, 246] as [number, number, number],
};

export function generatePDF(data: PDFExportData) {
  const {
    festivalSettings,
    collections,
    expenses,
    teamMembers,
    allTransactions,
    summary,
    dateRange,
    profileName,
  } = data;

  const filteredCollections = filterByDateRange(collections, dateRange.start, dateRange.end);
  const filteredExpenses = filterByDateRange(expenses, dateRange.start, dateRange.end);
  const filteredTransactions = filterByDateRange(allTransactions, dateRange.start, dateRange.end);

  const filteredTeamMembers = teamMembers.map((m) => {
    const filteredPayments = filterByDateRange(m.payments, dateRange.start, dateRange.end);
    const totalPaid = filteredPayments.reduce((s, p) => s + Number(p.amount), 0);
    const remaining = Number(m.total_contribution) - totalPaid;
    const status = totalPaid <= 0 ? 'NOT_PAID' : totalPaid >= Number(m.total_contribution) ? 'COMPLETED' : 'PARTIALLY_PAID';
    return { ...m, payments: filteredPayments, total_paid: totalPaid, remaining, status };
  });

  const totalReceived = filteredCollections.reduce((s, c) => s + Number(c.amount), 0) +
    filteredTeamMembers.reduce((s, m) => s + m.total_paid, 0);
  const totalExpenses = filteredExpenses.reduce((s, e) => s + Number(e.amount), 0);
  const remainingBalance = totalReceived - totalExpenses;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  let y = 20;

  // Helper: add page number footer
  const addFooter = () => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.gray);
      const pageStr = `Page ${i} of ${pageCount}`;
      doc.text(pageStr, pageWidth / 2, doc.internal.pageSize.getHeight() - 8, { align: 'center' });
      doc.text('Generated by Ganesh Chavithi Fund Manager', margin, doc.internal.pageSize.getHeight() - 8);
    }
  };

  // Helper: check page break
  const checkPageBreak = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
  };

  // Helper: section heading
  const sectionHeading = (text: string, color: [number, number, number] = COLORS.dark) => {
    checkPageBreak(20);
    y += 6;
    doc.setFillColor(...color);
    doc.rect(margin, y - 4, pageWidth - margin * 2, 0.8, 'F');
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...color);
    doc.text(text, margin, y + 4);
    y += 12;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.dark);
  };

  // === HEADER ===
  doc.setFillColor(...COLORS.dark);
  doc.rect(0, 0, pageWidth, 28, 'F');
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('🙏 GANESH CHAVITHI FINANCIAL REPORT', pageWidth / 2, 12, { align: 'center' });
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(festivalSettings?.festival_name || 'Ganesh Chavithi 2026', pageWidth / 2, 19, { align: 'center' });
  doc.text(`Report by: ${profileName}`, pageWidth / 2, 24, { align: 'center' });

  y = 36;
  doc.setTextColor(...COLORS.dark);

  // Report generated date/time
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.gray);
  const now = new Date();
  const reportDate = now.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
  const reportTime = now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
  doc.text(`Report Generated: ${reportDate} at ${reportTime}`, margin, y);

  if (dateRange.start || dateRange.end) {
    const startStr = dateRange.start ? formatDate(dateRange.start) : 'Beginning';
    const endStr = dateRange.end ? formatDate(dateRange.end) : 'Latest';
    doc.text(`Date Range: ${startStr} to ${endStr}`, margin, y + 5);
    y += 5;
  }

  if (festivalSettings?.start_date && festivalSettings?.end_date) {
    doc.text(
      `Festival Period: ${formatDate(festivalSettings.start_date)} to ${formatDate(festivalSettings.end_date)}`,
      margin,
      y + 5
    );
    y += 5;
  }

  y += 8;

  // === FINANCIAL SUMMARY ===
  sectionHeading('FINANCIAL SUMMARY');

  const summaryData = [
    ['Total Money Received', formatCurrencyPlain(totalReceived)],
    ['Total Expenses', formatCurrencyPlain(totalExpenses)],
    ['Remaining Balance', formatCurrencyPlain(remainingBalance)],
    ['Total Transactions', String(filteredTransactions.length)],
  ];

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'striped',
    headStyles: { fillColor: COLORS.dark, fontSize: 10 },
    bodyStyles: { fontSize: 10 },
    columnStyles: { 0: { cellWidth: 100 }, 1: { cellWidth: 60, halign: 'right' } },
    didParseCell: (data) => {
      if (data.section === 'body') {
        if (data.row.index === 0) data.cell.styles.textColor = COLORS.green;
        if (data.row.index === 1) data.cell.styles.textColor = COLORS.red;
        if (data.row.index === 2) data.cell.styles.textColor = COLORS.green;
        if (data.row.index === 2) data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  y = (doc as any).lastAutoTable.finalY + 4;

  // === MONEY RECEIVED (GREEN) ===
  sectionHeading('🟢 MONEY RECEIVED', COLORS.green);

  const moneyReceivedRows: string[][] = [
    ...filteredCollections.map((c) => [
      formatDate(c.date),
      c.time,
      c.person_name,
      'Collection',
      `+${formatCurrencyPlain(Number(c.amount))}`,
    ]),
    ...filteredTeamMembers.flatMap((m) =>
      m.payments.map((p) => [
        formatDate(p.date),
        p.time,
        m.name,
        'Team Payment',
        `+${formatCurrencyPlain(Number(p.amount))}`,
      ])
    ),
  ].sort((a, b) => (a[0] + a[1]).localeCompare(b[0] + b[1]));

  if (moneyReceivedRows.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.gray);
    doc.text('No money received records in this period.', margin, y + 4);
    y += 10;
  } else {
    autoTable(doc, {
      startY: y,
      head: [['Date', 'Time', 'Person', 'Type', 'Amount']],
      body: moneyReceivedRows,
      theme: 'striped',
      headStyles: { fillColor: COLORS.green, fontSize: 9 },
      bodyStyles: { fontSize: 9, textColor: COLORS.green },
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 25 },
        2: { cellWidth: 'auto' },
        3: { cellWidth: 35 },
        4: { cellWidth: 35, halign: 'right' },
      },
    });
    y = (doc as any).lastAutoTable.finalY + 4;

    // Total
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.green);
    doc.text(`Total Money Received: ${formatCurrencyPlain(totalReceived)}`, pageWidth - margin, y + 4, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.dark);
    y += 10;
  }

  // === EXPENSES (RED) ===
  sectionHeading('🔴 EXPENSES', COLORS.red);

  const expenseRows = filteredExpenses
    .map((e) => [formatDate(e.date), e.time, e.expense_name, e.category, formatCurrencyPlain(Number(e.amount))])
    .sort((a, b) => (a[0] + a[1]).localeCompare(b[0] + b[1]));

  if (expenseRows.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.gray);
    doc.text('No expense records in this period.', margin, y + 4);
    y += 10;
  } else {
    autoTable(doc, {
      startY: y,
      head: [['Date', 'Time', 'Expense', 'Category', 'Amount']],
      body: expenseRows,
      theme: 'striped',
      headStyles: { fillColor: COLORS.red, fontSize: 9 },
      bodyStyles: { fontSize: 9, textColor: COLORS.red },
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 25 },
        2: { cellWidth: 'auto' },
        3: { cellWidth: 35 },
        4: { cellWidth: 35, halign: 'right' },
      },
    });
    y = (doc as any).lastAutoTable.finalY + 4;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.red);
    doc.text(`Total Expenses: ${formatCurrencyPlain(totalExpenses)}`, pageWidth - margin, y + 4, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.dark);
    y += 10;
  }

  // === TEAM MEMBER CONTRIBUTIONS ===
  sectionHeading('👥 TEAM MEMBER CONTRIBUTIONS');

  const teamRows = filteredTeamMembers.map((m) => [
    m.name,
    formatCurrencyPlain(Number(m.total_contribution)),
    formatCurrencyPlain(m.total_paid),
    formatCurrencyPlain(m.remaining),
    m.status === 'COMPLETED' ? 'COMPLETED' : m.status === 'PARTIALLY_PAID' ? 'PARTIALLY PAID' : 'NOT PAID',
  ]);

  if (teamRows.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.gray);
    doc.text('No team members added.', margin, y + 4);
    y += 10;
  } else {
    autoTable(doc, {
      startY: y,
      head: [['Member', 'Total Contribution', 'Paid', 'Remaining', 'Status']],
      body: teamRows,
      theme: 'striped',
      headStyles: { fillColor: COLORS.dark, fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      columnStyles: {
        0: { cellWidth: 'auto' },
        1: { cellWidth: 35, halign: 'right' },
        2: { cellWidth: 30, halign: 'right' },
        3: { cellWidth: 30, halign: 'right' },
        4: { cellWidth: 35, halign: 'center' },
      },
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 4) {
          const status = data.cell.text[0];
          if (status === 'COMPLETED') data.cell.styles.textColor = COLORS.green;
          else if (status === 'PARTIALLY PAID') data.cell.styles.textColor = COLORS.yellow;
          else if (status === 'NOT PAID') data.cell.styles.textColor = COLORS.red;
        }
        if (data.section === 'body' && data.column.index === 2) {
          data.cell.styles.textColor = COLORS.green;
        }
        if (data.section === 'body' && data.column.index === 3) {
          data.cell.styles.textColor = COLORS.yellow;
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 4;
  }

  // === Team Member Payment History ===
  const membersWithPayments = filteredTeamMembers.filter((m) => m.payments.length > 0);
  if (membersWithPayments.length > 0) {
    sectionHeading('TEAM MEMBER PAYMENT HISTORY');
    let first = true;
    for (const m of membersWithPayments) {
      if (!first) y += 4;
      first = false;
      checkPageBreak(20);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.dark);
      doc.text(`${m.name} - Total: ${formatCurrencyPlain(Number(m.total_contribution))}, Paid: ${formatCurrencyPlain(m.total_paid)}, Remaining: ${formatCurrencyPlain(m.remaining)}`, margin, y);
      y += 4;

      const payRows = m.payments.map((p) => [
        formatDate(p.date),
        p.time,
        formatCurrencyPlain(Number(p.amount)),
        p.note || '-',
      ]);

      autoTable(doc, {
        startY: y,
        head: [['Date', 'Time', 'Amount', 'Note']],
        body: payRows,
        theme: 'striped',
        headStyles: { fillColor: COLORS.gray, fontSize: 8 },
        bodyStyles: { fontSize: 8 },
        columnStyles: {
          0: { cellWidth: 35 },
          1: { cellWidth: 25 },
          2: { cellWidth: 30, halign: 'right' },
          3: { cellWidth: 'auto' },
        },
      });
      y = (doc as any).lastAutoTable.finalY + 4;
    }
  }

  // === DAILY FINANCIAL SUMMARY ===
  sectionHeading('DAILY FINANCIAL SUMMARY');

  const dateMap: Record<string, { received: number; expenses: number }> = {};
  filteredCollections.forEach((c) => {
    if (!dateMap[c.date]) dateMap[c.date] = { received: 0, expenses: 0 };
    dateMap[c.date].received += Number(c.amount);
  });
  filteredTeamMembers.forEach((m) => {
    m.payments.forEach((p) => {
      if (!dateMap[p.date]) dateMap[p.date] = { received: 0, expenses: 0 };
      dateMap[p.date].received += Number(p.amount);
    });
  });
  filteredExpenses.forEach((e) => {
    if (!dateMap[e.date]) dateMap[e.date] = { received: 0, expenses: 0 };
    dateMap[e.date].expenses += Number(e.amount);
  });

  const dailyRows = Object.entries(dateMap)
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([date, vals]) => [
      formatDate(date),
      formatCurrencyPlain(vals.received),
      formatCurrencyPlain(vals.expenses),
      formatCurrencyPlain(vals.received - vals.expenses),
    ]);

  if (dailyRows.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.gray);
    doc.text('No daily data available.', margin, y + 4);
    y += 10;
  } else {
    autoTable(doc, {
      startY: y,
      head: [['Date', 'Money Received', 'Expenses', 'Net']],
      body: dailyRows,
      theme: 'striped',
      headStyles: { fillColor: COLORS.dark, fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 40, halign: 'right' },
        2: { cellWidth: 40, halign: 'right' },
        3: { cellWidth: 40, halign: 'right' },
      },
      didParseCell: (data) => {
        if (data.section === 'body') {
          if (data.column.index === 1) data.cell.styles.textColor = COLORS.green;
          if (data.column.index === 2) data.cell.styles.textColor = COLORS.red;
          if (data.column.index === 3) {
            data.cell.styles.textColor = data.cell.text[0].includes('-') ? COLORS.red : COLORS.green;
          }
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 4;

    // Totals row
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.green);
    doc.text(`Total Received: ${formatCurrencyPlain(totalReceived)}`, margin, y + 4);
    doc.setTextColor(...COLORS.red);
    doc.text(`Total Expenses: ${formatCurrencyPlain(totalExpenses)}`, pageWidth / 2, y + 4);
    const balanceColor = remainingBalance >= 0 ? COLORS.green : COLORS.red;
    doc.setTextColor(balanceColor[0], balanceColor[1], balanceColor[2]);
    doc.text(`Net: ${formatCurrencyPlain(remainingBalance)}`, pageWidth - margin, y + 4, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.dark);
    y += 12;
  }

  // === REMAINING BALANCE (GREEN, PROMINENT) ===
  y += 10;
  checkPageBreak(30);
  doc.setFillColor(...(remainingBalance >= 0 ? COLORS.green : COLORS.red));
  doc.rect(margin, y, pageWidth - margin * 2, 20, 'F');
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('REMAINING BALANCE', pageWidth / 2, y + 8, { align: 'center' });
  doc.setFontSize(20);
  doc.text(formatCurrencyPlain(remainingBalance), pageWidth / 2, y + 16, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.dark);

  // Add footers with page numbers
  addFooter();

  // Generate filename
  let filename: string;
  if (dateRange.start && dateRange.end) {
    const startStr = new Date(dateRange.start + 'T00:00:00').toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).replace(/\s/g, '-');
    const endStr = new Date(dateRange.end + 'T00:00:00').toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).replace(/\s/g, '-');
    filename = `Ganesh_Chavithi_Report_${startStr}_to_${endStr}.pdf`;
  } else {
    filename = 'Ganesh_Chavithi_Financial_Report_2026.pdf';
  }

  doc.save(filename);
}
